import { readFileSync, existsSync, statSync } from "node:fs";

export interface FileCheck {
  path: string;
  exists: boolean;
  sections: string[];
  missingSections: string[];
  headingOnlyGaps: string[];
  thinSections: string[];
  boilerplate: boolean;
  score: number;
}

export interface AuditReport {
  repoPath: string;
  files: FileCheck[];
  ciSystems: string[];
  aiReadinessScore: number;
  timestamp: string;
}

export interface ExpectedSection {
  label: string;
  stems: string[];
}

export interface GitHubRepo {
  owner: string;
  repo: string;
}

export const REQUIRED_FILES: Record<string, ExpectedSection[]> = {
  "README.md": [
    {
      label: "overview",
      stems: ["overview", "descript", "about", "introduct"],
    },
    {
      label: "quick start",
      stems: ["quick", "start", "getting", "install", "build"],
    },
    { label: "prerequisites", stems: ["prerequisit", "require"] },
    { label: "contributing", stems: ["contribut"] },
  ],
  "CONTRIBUTING.md": [
    {
      label: "dev setup",
      stems: ["setup", "install", "getting", "coding", "contribut", "build"],
    },
    {
      label: "coding standards",
      stems: ["standard", "style", "convention", "lint", "format"],
    },
    {
      label: "PR process",
      stems: ["pull", "request", "submit", "review", "pr"],
    },
    { label: "testing", stems: ["test"] },
  ],
  "AGENTS.md": [
    { label: "overview", stems: ["overview", "project", "structur"] },
    {
      label: "conventions",
      stems: ["convention", "pattern", "standard", "naming"],
    },
    { label: "review guidelines", stems: ["review", "guidelin"] },
  ],
  "ARCHITECTURE.md": [
    { label: "components", stems: ["component", "modul", "structur", "view"] },
    { label: "data flow", stems: ["flow", "data", "how", "work", "pipeline"] },
    {
      label: "dependencies",
      stems: ["dependen", "stack", "package", "librar", "service"],
    },
  ],
  ".coderabbit.yaml": [],
  "CLAUDE.md": [
    {
      label: "context pointers",
      stems: ["agent", "architectur", "contribut", "context"],
    },
    {
      label: "quick reference",
      stems: ["reference", "rule", "convention", "stack"],
    },
  ],
};

export const PLACEHOLDER_PATTERNS = [
  /\bTODO\b/i,
  /\bTBD\b/i,
  /\bFIXME\b/i,
  /\bXXX\b/i,
  /\bHACK\b/i,
  /\bWIP\b/i,
  /\bfill in later\b/i,
];

export const BOILERPLATE_PATTERNS = [
  /\bminimal template\b/i,
  /\bExamplePage\b/,
  /\bconsole-template\b/i,
  /\bscaffolded? (from|by|using)\b/i,
  /\bthis is a (starter|boilerplate|template)\b/i,
  /\bgenerated by\b/i,
  /\breplace (this|with your)\b/i,
  /\byour project (name|description)\b/i,
];

export const LINE_LIMITS: Record<string, number> = {
  "CLAUDE.md": 40,
  ".cursor/rules/*.mdc": 30,
};

export const CI_INDICATORS: { path: string; label: string }[] = [
  { path: ".github/workflows", label: "GitHub Actions" },
  { path: ".gitlab-ci.yml", label: "GitLab CI" },
  { path: ".ci-operator.yaml", label: "Prow / CI Operator" },
  { path: "Jenkinsfile", label: "Jenkins" },
  { path: "OWNERS", label: "Prow OWNERS" },
  { path: ".circleci/config.yml", label: "CircleCI" },
  { path: ".travis.yml", label: "Travis CI" },
  { path: "azure-pipelines.yml", label: "Azure Pipelines" },
  { path: ".drone.yml", label: "Drone CI" },
  { path: "Makefile", label: "Makefile" },
];

export const CI_HEADING_STEMS = [
  "ci",
  "prow",
  "pipeline",
  "automation",
  "workflow",
  "continuous",
];

export const SETUP_COMMAND_PATTERNS = [
  // Node.js
  /\bnpm install\b/,
  /\bnpm ci\b/,
  /\byarn install\b/,
  /\bpnpm install\b/,
  /\bnpm start\b/,
  /\bnpm run dev\b/,
  /\byarn dev\b/,
  /\bpnpm dev\b/,
  // Go
  /\bgo mod download\b/,
  /\bgo mod tidy\b/,
  /\bgo build\b/,
  /\bgo install\b/,
  /\bgo run\b/,
  // Python
  /\bpip3? install\b/,
  /\bpoetry install\b/,
  /\bpipenv install\b/,
  // Rust
  /\bcargo build\b/,
  /\bcargo install\b/,
  // Java / Kotlin
  /\bmvn install\b/,
  /\bmvn clean\b/,
  /\bgradle\w* build\b/,
  // Ruby
  /\bbundle install\b/,
  /\bgem install\b/,
  // .NET
  /\bdotnet restore\b/,
  /\bdotnet build\b/,
  // Generic
  /\bmake install\b/,
  /\bmake build\b/,
  /\bcmake\b/,
];

export const FILE_DESCRIPTIONS: Record<string, string> = {
  "README.md": "Repo-level foundational context for developers",
  "CONTRIBUTING.md": "Contribution conventions for humans and agents",
  "AGENTS.md": "AI-specific guidance and repo conventions",
  "ARCHITECTURE.md": "System design and component relationships",
  ".coderabbit.yaml": "CodeRabbit AI code review configuration",
  "CLAUDE.md": "Claude Code project context with pointers to detailed docs",
  ".cursor/rules/*.mdc":
    "Cursor project rules with conventions and context pointers",
};

export function parseArgs(argv: string[]): Record<string, string | boolean> {
  const args: Record<string, string | boolean> = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--help") {
      args.help = true;
      return args;
    }
    if (argv[i] === "--dry-run") {
      args["dry-run"] = true;
    } else if (argv[i] === "--verbose") {
      args.verbose = true;
    } else if (argv[i].startsWith("--") && i + 1 < argv.length) {
      args[argv[i].slice(2)] = argv[++i];
    }
  }
  return args;
}

export function extractHeadings(content: string): string[] {
  return content
    .split("\n")
    .filter((l) => l.startsWith("#"))
    .map((l) => l.replace(/^#+\s*/, "").toLowerCase());
}

export function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean);
}

export function headingMatchesStem(
  headingTokens: string[],
  stem: string,
): boolean {
  return headingTokens.some(
    (token) => token.startsWith(stem) || stem.startsWith(token),
  );
}

export function sectionFound(
  headings: string[],
  section: ExpectedSection,
): boolean {
  return headings.some((heading) => {
    const tokens = tokenize(heading);
    return section.stems.some((stem) => headingMatchesStem(tokens, stem));
  });
}

export function findMissingSections(
  headings: string[],
  expected: ExpectedSection[],
): string[] {
  return expected
    .filter((section) => !sectionFound(headings, section))
    .map((section) => section.label);
}

interface Section {
  heading: string;
  level: number;
  body: string;
}

function headingLevel(line: string): number {
  const match = /^(#+)/.exec(line);
  return match ? match[1].length : 0;
}

export function extractSections(content: string): Section[] {
  const lines = content.split("\n");
  const sections: Section[] = [];
  let currentHeading = "";
  let currentLevel = 0;
  let bodyLines: string[] = [];

  for (const line of lines) {
    const lvl = headingLevel(line);
    if (lvl > 0) {
      if (currentHeading) {
        sections.push({
          heading: currentHeading,
          level: currentLevel,
          body: bodyLines.join("\n"),
        });
      }
      currentHeading = line.replace(/^#+\s*/, "").toLowerCase();
      currentLevel = lvl;
      bodyLines = [];
    } else {
      bodyLines.push(line);
    }
  }
  if (currentHeading) {
    sections.push({
      heading: currentHeading,
      level: currentLevel,
      body: bodyLines.join("\n"),
    });
  }
  return sections;
}

export function findThinSections(
  content: string,
  expected: ExpectedSection[],
  minChars = 50,
): string[] {
  const sections = extractSections(content);
  const thin: string[] = [];

  for (const exp of expected) {
    const idx = sections.findIndex((s) => {
      const tokens = tokenize(s.heading);
      return exp.stems.some((stem) => headingMatchesStem(tokens, stem));
    });
    if (idx < 0) continue;

    const matched = sections[idx];
    let fullBody = matched.body;
    for (let i = idx + 1; i < sections.length; i++) {
      if (sections[i].level <= matched.level) break;
      fullBody += "\n" + sections[i].body;
    }

    const nonWhitespace = fullBody.replace(/\s+/g, "").length;
    if (nonWhitespace < minChars) {
      thin.push(exp.label);
    }
  }
  return thin;
}

export function findHeadingOnlyGaps(
  content: string,
  missing: ExpectedSection[],
): string[] {
  const bodyText = content
    .split("\n")
    .filter((l) => !l.startsWith("#"))
    .join("\n")
    .toLowerCase();

  return missing
    .filter((section) =>
      section.stems.some((stem) => new RegExp(`\\b${stem}\\w*\\b`).test(bodyText)),
    )
    .map((section) => section.label);
}

export function headingToSlug(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function parseGitRemoteUrl(url: string): GitHubRepo | null {
  const httpsMatch = /^https:\/\/github\.com\/([^/]+)\/([^/.]+)/.exec(url);
  if (httpsMatch) return { owner: httpsMatch[1], repo: httpsMatch[2] };

  const sshMatch = /^git@github\.com:([^/]+)\/([^/.]+)/.exec(url);
  if (sshMatch) return { owner: sshMatch[1], repo: sshMatch[2] };

  return null;
}

const DEFAULT_CACHE_MAX_AGE_MS = 24 * 60 * 60 * 1000;

export function isCacheFresh(
  filePath: string,
  maxAgeMs = DEFAULT_CACHE_MAX_AGE_MS,
): boolean {
  if (!existsSync(filePath)) return false;
  return Date.now() - statSync(filePath).mtimeMs < maxAgeMs;
}

export function prCacheFilePath(owner: string, repo: string): string {
  return `agents/repo-contextification/data/cache/${owner}-${repo}-pr-research.md`;
}

export function extractHeadingsFromFile(filePath: string): string[] {
  if (!existsSync(filePath)) return [];
  const content = readFileSync(filePath, "utf-8");
  return extractHeadings(content);
}
